[tool.poetry]
name = "hub"
version = "0.1.0"
description = ""
authors = ["linuseing <linus@r13.de>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
