EVENT_PLAYBACK_STOPPED = "spotify.playback.stopped"
EVENT_PLAYBACK_RESUMED = "spotify.playback.resumed"
EVENT_PLAYBACK_STARTED = "spotify.playback.started"
EVENT_TRACK_CHANGE = "spotify.track.change"
EVENT_PLAYBACK_DEVICE_CHANGE = "spotify.playback.device_change"
