ACTIVE = 'active'
CONFIG = 'config'
SUSPEND_ON_ERROR = 'suspend_on_error'
PASS_THROUGH_BEHAVIOR = 'pass_through'

PASS_THROUGH_EXCEPT_FORMATTER = 'except-formatter'
PASS_THROUGH_ALWAYS = 'always'
PASS_THROUGH_NEVER = 'never'

DEFAULT_SETTINGS_MICRO = {
    ACTIVE: True,
    SUSPEND_ON_ERROR: False,
    PASS_THROUGH_BEHAVIOR: PASS_THROUGH_EXCEPT_FORMATTER
}
